spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/lap
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
